package Login;

import Connection.ConnectionToDB;
import Customer.CustomerDashboard;
import Admin.AdminDashboard;
import Customer.Customer;
import Customer.CustomerDashboard;
import Employee.EmployeeDashboard;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    ConnectionToDB con_obj = new ConnectionToDB();
    LoginOperation op = new LoginOperation();
    
    public String userID;
    public String userPassword;
    public String userRole;

    public Login() {
        initComponents();
        con_obj.EstablishConnection();
        String userID;
        String userPassword;
        String userRole;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_panel1 = new javax.swing.JPanel();
        lbl_bankLogo = new javax.swing.JLabel();
        lbl_logoHeading1 = new javax.swing.JLabel();
        lbl_logoHeading2 = new javax.swing.JLabel();
        lbl_infoEmail = new javax.swing.JLabel();
        lbl_infoUAN = new javax.swing.JLabel();
        pnl_panel2 = new javax.swing.JPanel();
        lbl_sloganHeading = new javax.swing.JLabel();
        lbl_signIn = new javax.swing.JLabel();
        spr_separator1 = new javax.swing.JSeparator();
        lbl_idHeading = new javax.swing.JLabel();
        lbl_userPic = new javax.swing.JLabel();
        txt_loginId = new javax.swing.JTextField();
        lbl_passwordPic = new javax.swing.JLabel();
        lbl_passwordHeading = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_roleHeading = new javax.swing.JLabel();
        lbl_rolePic = new javax.swing.JLabel();
        cmb_role = new javax.swing.JComboBox();
        spr_separator2 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        lbl_eyePic = new javax.swing.JLabel();
        chk_showPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnl_panel1.setBackground(new java.awt.Color(153, 153, 153));
        pnl_panel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(198, 160, 89)));
        pnl_panel1.setPreferredSize(new java.awt.Dimension(250, 250));

        lbl_bankLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bank Logo.png"))); // NOI18N

        lbl_logoHeading1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lbl_logoHeading1.setText("Celestial Finance Ltd.");

        lbl_logoHeading2.setBackground(new java.awt.Color(0, 0, 0));
        lbl_logoHeading2.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        lbl_logoHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logoHeading2.setText("Since 1988");

        lbl_infoEmail.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        lbl_infoEmail.setText("Email: feedback@CelestialFinance.com");

        lbl_infoUAN.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        lbl_infoUAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_infoUAN.setText("UAN: 111-912-912");

        javax.swing.GroupLayout pnl_panel1Layout = new javax.swing.GroupLayout(pnl_panel1);
        pnl_panel1.setLayout(pnl_panel1Layout);
        pnl_panel1Layout.setHorizontalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_logoHeading1)
                            .addComponent(lbl_infoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lbl_logoHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lbl_bankLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_infoUAN, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_panel1Layout.setVerticalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lbl_bankLogo)
                .addGap(0, 0, 0)
                .addComponent(lbl_logoHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_logoHeading2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_infoUAN)
                .addGap(0, 0, 0)
                .addComponent(lbl_infoEmail)
                .addGap(22, 22, 22))
        );

        pnl_panel2.setBackground(new java.awt.Color(51, 51, 51));
        pnl_panel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(198, 160, 89)));

        lbl_sloganHeading.setBackground(new java.awt.Color(36, 37, 42));
        lbl_sloganHeading.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        lbl_sloganHeading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sloganHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sloganHeading.setText("Your Future, Our Priority.");
        lbl_sloganHeading.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(198, 160, 89)));
        lbl_sloganHeading.setOpaque(true);

        lbl_signIn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbl_signIn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_signIn.setText("SIGN IN");

        lbl_idHeading.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_idHeading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_idHeading.setText("Login ID:");

        lbl_userPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User Golden.png"))); // NOI18N

        txt_loginId.setBackground(new java.awt.Color(36, 37, 42));
        txt_loginId.setForeground(new java.awt.Color(255, 255, 255));
        txt_loginId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(198, 160, 89)));
        txt_loginId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginIdActionPerformed(evt);
            }
        });

        lbl_passwordPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lock Golden.png"))); // NOI18N

        lbl_passwordHeading.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_passwordHeading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_passwordHeading.setText("Password:");

        txt_password.setBackground(new java.awt.Color(36, 37, 42));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setText("password");
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(198, 160, 89)));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
        });

        lbl_roleHeading.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_roleHeading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_roleHeading.setText("Role:");

        lbl_rolePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Role Golden.png"))); // NOI18N

        cmb_role.setBackground(new java.awt.Color(36, 37, 42));
        cmb_role.setForeground(new java.awt.Color(255, 255, 255));
        cmb_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Customer", "Employee", " " }));
        cmb_role.setToolTipText("");
        cmb_role.setAutoscrolls(true);
        cmb_role.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(198, 160, 89)));
        cmb_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_roleActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(198, 160, 89));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_eyePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye.png"))); // NOI18N

        chk_showPassword.setBackground(new java.awt.Color(65, 67, 77));
        chk_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_panel2Layout = new javax.swing.GroupLayout(pnl_panel2);
        pnl_panel2.setLayout(pnl_panel2Layout);
        pnl_panel2Layout.setHorizontalGroup(
            pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_sloganHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_panel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spr_separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_panel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_panel2Layout.createSequentialGroup()
                                .addComponent(lbl_userPic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_loginId, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idHeading)
                            .addGroup(pnl_panel2Layout.createSequentialGroup()
                                .addComponent(lbl_passwordPic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_passwordHeading)
                            .addGroup(pnl_panel2Layout.createSequentialGroup()
                                .addComponent(lbl_rolePic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_roleHeading))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_eyePic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_showPassword))
                    .addComponent(spr_separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        pnl_panel2Layout.setVerticalGroup(
            pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel2Layout.createSequentialGroup()
                .addComponent(lbl_sloganHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbl_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spr_separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_idHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_userPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_loginId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_passwordHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chk_showPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_passwordPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_eyePic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_roleHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_rolePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spr_separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_loginIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginIdActionPerformed

    private void cmb_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_roleActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        userID = txt_loginId.getText();

        char[] pass = txt_password.getPassword();
        userPassword = new String(pass);

        userRole= (String) cmb_role.getSelectedItem();

        boolean b = op.LoginUser(userID, userPassword, userRole);
        Customer cus = new Customer();
        
        cus.getDetails(userID);
        
        if (b) {
            JOptionPane.showMessageDialog(null, "Login Successful.");
            if (userRole == "Customer") {
                CustomerDashboard dashboard = new CustomerDashboard();
                dashboard.showDashboard();
                dashboard.setVisible(true);
                this.setVisible(false);
            } else if (userRole == "Admin") {
                AdminDashboard dashboard = new AdminDashboard();
                dashboard.showDashboard();
                dashboard.setVisible(true);
                this.setVisible(false);
            } else {
                EmployeeDashboard dashboard = new EmployeeDashboard();
                dashboard.showDashboard();
                dashboard.setVisible(true);
                this.setVisible(false);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Login Denied.");
            JOptionPane.showMessageDialog(null, "LoginID, Password or Role incorrect.");
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    private void chk_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_showPasswordActionPerformed
        if (chk_showPassword.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }

    }//GEN-LAST:event_chk_showPasswordActionPerformed

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:
        if (txt_password.getText().equals("password")){
            txt_password.setText(null);
        }
    }//GEN-LAST:event_txt_passwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox chk_showPassword;
    private javax.swing.JComboBox cmb_role;
    private javax.swing.JLabel lbl_bankLogo;
    private javax.swing.JLabel lbl_eyePic;
    private javax.swing.JLabel lbl_idHeading;
    private javax.swing.JLabel lbl_infoEmail;
    private javax.swing.JLabel lbl_infoUAN;
    private javax.swing.JLabel lbl_logoHeading1;
    private javax.swing.JLabel lbl_logoHeading2;
    private javax.swing.JLabel lbl_passwordHeading;
    private javax.swing.JLabel lbl_passwordPic;
    private javax.swing.JLabel lbl_roleHeading;
    private javax.swing.JLabel lbl_rolePic;
    private javax.swing.JLabel lbl_signIn;
    private javax.swing.JLabel lbl_sloganHeading;
    private javax.swing.JLabel lbl_userPic;
    private javax.swing.JPanel pnl_panel1;
    private javax.swing.JPanel pnl_panel2;
    private javax.swing.JSeparator spr_separator1;
    private javax.swing.JSeparator spr_separator2;
    private javax.swing.JTextField txt_loginId;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
